TrabajoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('paginas.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('turnos/', include('turnos.urls')),
    path('historial/', include('historial.urls')),
    path('productos/', include('productos.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('taller/', include('taller.urls')),
    path('gerencia/', include('gerencia.urls')),
]

pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("crear", views.CrearPedido, name="crearpedido"),
    path("<int:id_pedido>", views.VerPedido, name="verpedido"),
    path("<int:id_pedido>/modificar", views.ModificarPedido, name="modificarpedido"),
    path("<int:id_pedido>/eliminar", views.EliminarPedido, name="eliminarpedido"),
    path("seleccionaritem", views.SeleccionarItem, name="seleccionaritem"),
    path("<int:id_pedido>/agregaritem/<int:id_item>", views.AgregarItem, name="agregaritem"),
    path("<int:id_pedido>/modificaritem/<int:id_itempedido>", views.ModificarItem, name="modificaritem"),
]

taller/urls.py
from django.urls import path
from . import views

app_name = 'taller'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("<int:id_pedido>/verpedido", views.VerPedido, name="verpedido"),
    path("<int:id_pedido>/cambiarestado", views.CambiarEstado, name="cambiarestado"),
]

pedidos/models.py
from django.db import models
from pacientes.models import Paciente
from productos.models import Producto
from django.contrib.auth.models import User, Group


class Pedido(models.Model):    
    ESTADO_DE_PEDIDO = [
        (0, 'pendiente'),
        (1, 'pedido'),
        (2, 'taller'),
        (3, 'finalizado'),
    ]
    OPCIONES_DE_PAGO = [
        (0, 'tarjeta de credito'),
        (1, 'tarjeta de debito'),
        (2, 'villetera virtual'),
        (3, 'efectivo'),
    ]
    fechahora = models.DateField() #models.DateTimeField()
    paciente = models.ForeignKey(Paciente, on_delete = models.RESTRICT, related_name='pedidopacientes')
    vendedor = models.ForeignKey(User, on_delete = models.RESTRICT, related_name='pedidovendedores')
    tipopago = models.IntegerField(choices=OPCIONES_DE_PAGO, default=1)
    estado = models.IntegerField(choices=ESTADO_DE_PEDIDO, default=1)
    
    def estado_str(self):
        return self.ESTADO_DE_PEDIDO[self.estado][1]

    def tipopago_str(self):
        return self.OPCIONES_DE_PAGO[self.tipopago][1]

    def vendedor_str(self):
        return self.vendedor.first_name.capitalize() + ', ' + self.vendedor.last_name.capitalize()

class PedidoItem(models.Model):    
    pedido = models.ForeignKey(Pedido, on_delete = models.CASCADE, related_name='pedidodeitem')
    item = models.ForeignKey(Producto, on_delete = models.RESTRICT, related_name='productodeitem') 
    cantidad = models.IntegerField(default=1)
    precio = models.FloatField(default=0)
    opcion = models.CharField(max_length=500)

    def __str__(self): 
        return self.item.nombre.capitalize() + ('' if self.opcion.strip() == '' else ' - ') + self.opcion.capitalize()

    def subtotal(self):
        return self.precio * self.cantidad

pedidos/forms.py
from django import forms
from django.forms.widgets import NumberInput
from django.contrib.auth.models import User
from pacientes.models import Paciente
from .models import Pedido, Producto, PedidoItem
from django.forms import ModelChoiceField
import datetime

class MyModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.first_name}, {obj.last_name}'

class FormPedido(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['fechahora', 'paciente', 'vendedor', 'tipopago', 'estado']

    fechahora = forms.DateField(initial=datetime.date.today, widget=NumberInput(attrs={'class': 'form-control', 'type': 'date'}))
    paciente = forms.ModelChoiceField(queryset=Paciente.objects.all(), widget=forms.Select(attrs={'autofocus': 'autofocus', 'class': 'form-control'}))
    vendedor = forms.ModelChoiceField(queryset=User.objects.all(), label='', widget=forms.Select(attrs={'hidden': 'True', 'class': 'form-control'}))
    tipopago = forms.ChoiceField(choices=Pedido.OPCIONES_DE_PAGO, widget=forms.Select(attrs={'class': 'form-control'}))
    estado = forms.ChoiceField(choices=Pedido.ESTADO_DE_PEDIDO, required=False, initial = Pedido.ESTADO_DE_PEDIDO[0][0], widget=forms.Select(attrs={'class': 'form-control'}))

class FormItemPedido(forms.ModelForm):
    class Meta:
        model = PedidoItem
        fields = ['cantidad', 'precio']

    cantidad = forms.IntegerField(initial=1, widget=NumberInput(attrs={'autofocus': 'autofocus', 'class': 'form-control'}))
    precio = forms.CharField(initial = 0, required = False, widget = forms.NumberInput(attrs={'id': 'form_homework', 'step': '0.1', 'class': 'form-control'})) 

pedidos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from usuarios.utilidades import *
from .models import Pedido, PedidoItem
from pacientes.models import Paciente
from .forms import *

def Listado(request):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: # es de ventas ?
        pedidos = Pedido.objects.filter() # obtiene la lista de pedidos
        contexto['pedidos'] = pedidos # guarda los pedidos en el contexto
        contexto['id_pedidoactual'] = request.session['id_pedidoactual'] if 'id_pedidoactual' in request.session else None # verifica id_pedidoactual en sesion
        return render(request, "pedidos/listado.html", contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def VerPedido(request, id_pedido):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: # es de ventas ?
        try:
            infopedido = get_object_or_404(Pedido, id = id_pedido)
            pedidos_det = PedidoItem.objects.filter(pedido_id=infopedido.id)
            # todo: crear total !!!
        except Exception:
            raise Http404('no existe el pedido')
        contexto['pedidos_det'] = pedidos_det
        contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = infopedido.id # guarda el id info pedido en la sesion y contexto
        contexto['infopedidoactual'] = infopedido # guarda el info pedido en el contexto
        return render(request, 'pedidos/pedido.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def CrearPedido(request):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: # es de ventas?
        vendedor = User.objects.get(id = contexto['id_usuario']) # busca al vendedor para el contexto                    contexto['id_pedidoactual'] = ''
        contexto['accion'] = 'Crear'
        form = FormPedido(request.POST or None)
        form.fields['vendedor'].initial = vendedor # se asigna el vendedor al form
        contexto['form'] = form # se guarda el form en el contexto
        if request.method == 'POST': # es un submit de crear pedido?
            if form.is_valid(): # es valido el form?
                infopedido = form.save() # se guarda el pedido y se asigna a infopedido
                contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = infopedido.id # guarda el id info pedido en la sesion y contexto
                contexto['infopedidoactual'] = infopedido # guarda el info pedido en el contexto y la sesion
                return redirect("pedidos:verpedido", id_pedido = infopedido.id)
            else: # no es un from válido
                contexto['resultado'] = 'form no valido'
                return HttpResponseRedirect(reverse("paginas:inicio"))
        else: # es un nuevo pedido
            contexto['infopedidoactual'] = request.session['infopedidoactual'] = None
            return render(request, 'pedidos/infopedido.html', contexto)
    else: # no es de ventas
        return HttpResponseRedirect(reverse("paginas:inicio"))

def ModificarPedido(request, id_pedido):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: # es vendedor ?
        if id_pedido == 0: # si es 0 limpia la sesion del pedido actual
            contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = ''
            return HttpResponseRedirect(reverse("pedidos:listado"))
        else:
            try:
                infopedido = get_object_or_404(Pedido, id = id_pedido)
            except Exception:
                raise Http404('no existe el pedido')

            contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = infopedido.id
            contexto['infopedidoactual'] = infopedido # guarda el pedido en el contexto
            if request.method == 'POST':
                form = FormPedido(request.POST, instance = infopedido)
                if form.is_valid():
                    form.save()    
                    return redirect("pedidos:verpedido", id_pedido = infopedido.id)
                else:
                    contexto['form'] = form
                    return render(request, 'pedidos/infopedido.html', contexto)
            else:
                form = FormPedido(instance = infopedido)
                form.fields['fechahora'].initial = datetime.datetime.now() # infopedido.fechahora
                contexto['form'] = form
                return render(request, 'pedidos/infopedido.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def EliminarPedido(request, id_pedido):
    pass

def SeleccionarItem(request):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: 
        try:
            id_pedido = request.session['id_pedidoactual'] # se obtiene el id_pedido actual de la sesion
            infopedido = get_object_or_404(Pedido, id = id_pedido) # se busca ese pedido en la bd
        except Exception:
            raise Http404('no hay pedido actual')

        contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = infopedido.id
        contexto['infopedido'] = infopedido # guarda el pedido en el contexto

        items = Producto.objects.filter(activo=True)
        contexto['items'] = items
        return render(request, 'pedidos/seleccionaritem.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def AgregarItem(request, id_pedido, id_item):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: 
        contexto['accion'] = 'Agregar item a pedido'
        try:
            infoPedido = get_object_or_404(Pedido, id = id_pedido)
            producto = get_object_or_404(Producto, id = id_item)
        except Exception:
            raise Http404('no existe el pedido o producto')

        opcion = producto.opcion # opcion = '1, 2, 3. a, b, c'
        op0 = [ [y.strip() for y in x.split(',')] for x in opcion.split('.')]
        contexto['opcion'] = op0 # op0 = '[[1, 2, 3],  [a, b, c]]'
        contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = infoPedido.id # guarda el idpedidoactual en contexto y sesion
        contexto['infopedido'] = infoPedido # guarda el pedido en el contexto
        contexto['producto'] = producto #guarda el producto en el contexto

        if request.method == 'POST':
            sel_opc = [] # recupera las opciones seleccionadas
            for opc in op0: # recorre las opciones del item db
                if str(opc) in request.POST: # la opcion está en el post del form ?
                    sel_opc.append(request.POST[str(opc)]) # entonces agrega a la sel_opc 
            sel_opc = ', '.join(sel_opc)
            pedidoItemNuevo = PedidoItem(pedido=infoPedido, item=producto, cantidad=request.POST['cantidad'], precio=request.POST['precio'], opcion=sel_opc)            
            pedidoItemNuevo.save()
            return redirect("pedidos:verpedido", id_pedido = infoPedido.id)
        else:
            pedidoItemNuevo = PedidoItem(pedido=infoPedido, item=producto, cantidad=1, precio=producto.precio, opcion=producto.opcion)
            form = FormItemPedido(instance = pedidoItemNuevo)
            contexto['form'] = form
            return render(request, 'pedidos/editaritem.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def ModificarItem(request, id_pedido, id_itempedido):
    contexto = logueadoComo(request, ['gerencia', 'ventas'])
    if contexto: 
        try:
            infoPedido = get_object_or_404(Pedido, id = id_pedido)
            pedidoItem = PedidoItem.objects.get(id = id_itempedido)
            producto = get_object_or_404(Producto, id = pedidoItem.item.id)
        except Exception:
            raise Http404('no se pudo recuperar la informacion del item')

        opcion = producto.opcion # opcion = '1, 2, 3. a, b, c'
        op0 = [ [y.strip() for y in x.split(',')] for x in opcion.split('.')]

        contexto['opcion'] = op0 # op0 = '[[1, 2, 3],  [a, b, c]]'
        contexto['id_pedidoactual'] = request.session['id_pedidoactual'] = infoPedido.id # guarda el idpedidoactual en contexto y sesion
        contexto['infopedido'] = infoPedido # guarda el pedido en el contexto
        contexto['producto'] = producto #guarda el producto en el contexto
        contexto['opcioneselegidas'] = [ op.strip() for op in pedidoItem.opcion.split(',')] # aca van las opciones elegidas del item de pedido

        if request.method == 'POST':
            form = FormItemPedido(request.POST, instance = pedidoItem)
            if form.is_valid():
                sel_opc = []
                for opc in op0: # recorre las opciones del item db
                    if str(opc) in request.POST: # la opcion está en el post del form ?
                        sel_opc.append(request.POST[str(opc)]) # entonces agrega a la sel_opc 
                sel_opc = ', '.join(sel_opc)
                pedidoItem.opcion = sel_opc
                pedidoItem.precio = precio=request.POST['precio']
                pedidoItem.cantidad = cantidad=request.POST['cantidad']
                pedidoItem.save()
                return redirect("pedidos:verpedido", id_pedido = infoPedido.id)
            else:
                print('>>>>>>>>>>> FORM NO VALIDO ')
        else:
            form = FormItemPedido(instance = pedidoItem)
            contexto['form'] = form
            return render(request, 'pedidos/editaritem.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

pedidos/templates/pedidos/editaritem.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Item {% endblock title %} 

{% block contenido %}
    <script type="text/javascript">
			milink = 'hola mundo'
	</script>
    <br>
    <h3> Item de pedido </h3>
    <div>Producto: <strong>id: {{ producto.id }} - {{ producto.nombre|title }}</strong></div>
    <br>
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <br>
        <div>Opciones:</div>
        {% for grupo in opcion %}
            <fieldset id="grupo">
            <br>
            {% for op in grupo %}
                <input type="radio" id="{{op}}" name="{{grupo}}" value="{{op}}" 
                {% if op in opcioneselegidas %}
                checked
                {% endif %}
                >
                <label for="{{op}}">{{op}}</label><br>
            {% endfor %}
            </fieldset>
        {% endfor %}
    <br>
    <input type="submit" class="btn btn-primary" value="Guardar"> 
    <input type="button" class="btn btn-secondary"  name="cancelar" value="Cancelar" onClick="location.href='{% url 'pedidos:verpedido' id_pedido=id_pedidoactual %}';" />  
    </form>
{% endblock contenido %}

pedidos/templates/pedidos/eliminar.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Eliminar item{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Eliminar item</h3>
    <br>
    <ul class="list-group">
        <li class="list-group-item list-group-item-action flex-column align-items-start"> 
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">
                    <div>Item: {{ producto }}</div>
                </h5>
                <small class="text-muted">precio: ${{ producto.precio }}</small>
            </div>
        </li>
    </ul>

    <br>
    <div>Realmente desea eliminar el item?</div>
    <br>

    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <input type="submit" class="btn btn-primary" value="Eliminar"> 
        <input type="button" class="btn btn-secondary"  name="cancelar" value="Cancelar" onClick="window.location.href=window.history.back();" />
    </form>
{% endblock contenido %}

pedidos/templates/pedidos/infopedido.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - {{ accion }} Información de Pedido {% endblock title %} 

{% block contenido %}
    <br>
    <h3>{{ accion }} Pedido </h3>
    <br>
    <ul>
    <form method = "POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <br>
        <input type="submit" class="btn btn-primary" value="Guardar"> 
        <input type="button" class="btn btn-secondary"  name="cancelar" value="Cancelar" onClick=
        {% if id_pedidoactual %}
        "location.href='{% url 'pedidos:verpedido' id_pedido=id_pedidoactual %}';" 
        {% else %}
        "history.back();;" 
        {% endif %}
        />
    </form>
{% endblock contenido %}

pedidos/templates/pedidos/listado.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Pedidos{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Pedidos</h3>
    <p>
        <a class="badge badge-primary " href="{% url 'pedidos:crearpedido' %}">nuevo</a>
    </p>
    <ul class="list-group">
        {% for pedido in pedidos %}
            <li class="list-group-item list-group-item-action flex-column align-items-start"> 
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Id: {{pedido.id}} - Paciente: {{pedido.paciente|title}}</h5>
                    <small class="text-muted">fecha: {{pedido.fechahora|date:"D d M Y"}} </small>
                </div>
                <div>Vendedor: {{ pedido.vendedor_str }}</div>
                <div>Estado: {{ pedido.estado_str|title }}</div>
                <div>
                    <a href="{% url 'pedidos:verpedido' pedido.id %}" class="badge badge-secondary">modificar</a>
                    <a href="#" class="badge badge-light ">eliminar</a>
                </div>
            </li>
        {% empty %}
            <li> no hay pedidos </li>
        {% endfor %}
    </ul>
{% endblock contenido %}

pedidos/templates/pedidos/pedido.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Pedido {% endblock title %} 

{% block contenido %}
    <br>
    <h3> Pedido </h3>
    <a href="{% url 'pedidos:modificarpedido' 0 %}" class="badge badge-primary">terminar edicion de pedido</a>
    <br><br>
    <ul class="list-group">
        <li class="list-group-item list-group-item-action flex-column align-items-start"> 
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Id: {{infopedidoactual.id}} - Paciente: {{infopedidoactual.paciente|title}}</h5>
                <small class="text-muted">Fecha: {{infopedidoactual.fechahora|date:"D d M Y"}}</small>
            </div>
            <div class="mb-1">Vendedor: {{ infopedidoactual.vendedor.first_name|title }}, {{ infopedidoactual.vendedor.last_name|title }}</div>
            <div class="mb-1">Estado: {{ infopedidoactual.estado_str|title }}</div>
            <div class="mb-1">Tipo de pago: {{ infopedidoactual.tipopago_str|title }}</div>
            {% if True %}
            <div>
                <a href="{% url 'pedidos:modificarpedido' infopedidoactual.id %}" class="badge badge-secondary">mofificar info</a>
            </div> 
            {% endif %}
        </li>
    </ul>
    <br>

    <ul class="list-group">
        <li class="list-group-item list-group- flex-column align-items-start"> 
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Items en pedido: </h5>
                <small class="text-muted"> {{total}} </small>
            </div>
            <div class="mb-1">
            <a href="{% url 'pedidos:seleccionaritem' %}" class="badge badge-secondary">agregar item</a>
            </div>
            <ul>
                {% for item_pedido in pedidos_det %}
                <li class="list-group-item list-group-item-action flex-column align-items-start"> 
                    <div class="d-flex w-100 justify-content-between">
                        <div class="mb-1">{{item_pedido}} </div>
                        <small class="text-muted">${{item_pedido.precio}} x {{item_pedido.cantidad}} unidad(es) : Subtotal: ${{ item_pedido.subtotal|stringformat:".2f" }}</small>
                    </div>
                    <a href="{% url 'pedidos:modificaritem' id_pedido=infopedidoactual.id id_itempedido=item_pedido.id %}" class="badge badge-secondary">modificar</a>
                </li>
                {% empty %}
                    no hay items en el pedido
                {% endfor %}
            </ul> 
        </li>
    </ul>
{% endblock contenido %}

pedidos/templates/pedidos/seleccionaritem.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Seleccionar Item{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Seleccionar Item para el pedido</h3>
    <p>
    </p>
    <a href="{% url 'pedidos:verpedido' id_pedidoactual %}" class="badge badge-primary">volver a pedido</a>
    <br><br>
    <ul class="list-group">
        {% for item in items %}
            <li class="list-group-item"> 
                Id: {{ item.id }} - <strong>{{ item|title }}</strong>
                <div>Opciones: {{ item.opcion|title }}</div>
                <div>
                    <a href="{% url 'pedidos:agregaritem' id_pedidoactual item.id %}" class="badge badge-secondary">agregar</a>
                </div>
            </li>

        {% empty %}
            <li> no hay items </li>
        {% endfor %}
    <ul>


{% endblock contenido %}