TrabajoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('paginas.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('turnos/', include('turnos.urls')),
    path('historial/', include('historial.urls')),
    path('productos/', include('productos.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('taller/', include('taller.urls')),
    path('gerencia/', include('gerencia.urls')),
]

historial/urls.py
from django.urls import path
from . import views

app_name = 'historial'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("<int:id_paciente>", views.HistorialPaciente, name="historialpaciente"),
    path("<int:id_paciente>/crear", views.CrearObservacion, name="crearobservacion"),
    path("modificarobservacion/<int:id_observacion>", views.ModificarObservacion, name="modificarobservacion"),
    path("eliminarobservacion/<int:id_observacion>", views.EliminarObservacion, name="eliminarobservacion"),
]

taller/urls.py
from django.urls import path
from . import views

app_name = 'taller'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("<int:id_pedido>/verpedido", views.VerPedido, name="verpedido"),
    path("<int:id_pedido>/cambiarestado", views.CambiarEstado, name="cambiarestado"),
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("crear/", views.CrearTurno, name="crear"),
    path("<int:id_turno>/modificar", views.ModificarTurno, name="modificarturno"),
    path("<int:id_turno>/eliminar", views.EliminarTurno, name="eliminarturno"),
    path("<int:id_turno>/alternaratendido", views.AlternarAtendido, name="alternaratendido"),
]

turnos/models.py
from django.db import models
from pacientes.models import Paciente
from django.contrib.auth.models import User, Group

class Turno(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete = models.RESTRICT, limit_choices_to={'activo': True}, related_name='turnopacientes')
    doctor = models.ForeignKey(User, on_delete = models.RESTRICT, related_name='turnodoctores')
    fecha = models.DateField()
    hora = models.IntegerField()
    atendido = models.BooleanField(default=False)

    class Meta:
        ordering = ['fecha', 'hora']
    
    def __str__(self):
        return f'{self.paciente.apellido.capitalize}, {self.paciente.nombre.capitalize}'

    def hora_str(self):
        strhora = str(self.hora)
        return strhora[:-2]+':'+strhora[-2:]

    def doctor_str(self):
        return self.doctor.first_name.capitalize() + ', ' + self.doctor.last_name.capitalize()

turnos/forms.py
from django import forms
from django.forms.widgets import NumberInput, DateTimeInput
from django.contrib.auth.models import User
from pacientes.models import Paciente
from .models import Turno
from django.forms import ModelChoiceField
import datetime

class MyModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return F'{obj.last_name.title()}, {obj.first_name.title()}'

horarios =  [ (n*100 + m, str(n) + ':' + str(m).zfill(2)) for n in range(8, 19) for m in [0, 15, 30, 45]]
class FormCrearTurno(forms.ModelForm):
    class Meta:
        model = Turno
        fields = '__all__'

    paciente = forms.ModelChoiceField(queryset=Paciente.objects.filter(activo=True), widget=forms.Select(attrs={'autofocus': 'autofocus', 'class': 'form-control'}))
    doctor = MyModelChoiceField(queryset=User.objects.filter(is_staff=False, groups__name='profesional'), widget=forms.Select(attrs={'class': 'form-control'}))
    fecha = forms.DateField(initial=datetime.date.today, widget=NumberInput(attrs={'type': 'date', 'class': 'form-control'}))
    hora = forms.ChoiceField(choices=horarios, widget=forms.Select(attrs={'class': 'form-control'}))    

opciones_fecha = [('0', 'Usar solo año'), ('1', 'Usar año y mes'), ('2', 'Usar año, mes y dia')]

class FormFiltroFecha(forms.Form):
    fecha = forms.DateField(initial=datetime.date.today, widget=NumberInput(attrs={'type': 'date', 'class': 'form-control'}) )
    opcionfecha = forms.CharField(label='Seleccione filtro', initial = opciones_fecha[1][0], widget = forms.RadioSelect(choices = opciones_fecha))

turnos/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django import forms
from datetime import datetime
from usuarios.utilidades import *
from .models import Turno
from .forms import FormCrearTurno, FormFiltroFecha

def Listado(request):
    contexto = logueadoComo(request, ['gerencia', 'profesional', 'secretaria'])
    if contexto: 
        if 'profesional' in contexto['grupos']: # es un doctor?
            turnos = Turno.objects.filter(doctor = request.user) # filtra solo sus pacientes
        else:
            turnos = Turno.objects.all().order_by('-fecha', '-hora')

        if request.method == 'POST': # form posteado con valores ?
            form = FormFiltroFecha(initial = request.POST) # carga el form con valores posteados

            anio = request.POST['fecha'][0:4]
            mes = request.POST['fecha'][5:7]
            dia = request.POST['fecha'][8:10]
            opcionfecha = request.POST['opcionfecha']

            if opcionfecha == '0':
                turnos = turnos.filter(fecha__year=anio)
                contexto['filtro'] = f'Año = {anio}'
            elif opcionfecha == '1':
                turnos = turnos.filter(fecha__year=anio, fecha__month=mes)
                contexto['filtro'] = f'Mes / Año = {mes} / {anio}'
            elif opcionfecha == '2':
                turnos = turnos.filter(fecha__year=anio, fecha__month=mes, fecha__day=dia)
                contexto['filtro'] = f'Fecha = {dia} / {mes} / {anio}'
        else: # inicial sin post
            anio = datetime.now().year
            mes = datetime.now().month
            turnos = turnos.filter(fecha__year = anio, fecha__month = mes)
            contexto['filtro'] =  f'Mes / Año = {mes} / {anio}'
            form = FormFiltroFecha(initial = {'usarmes': True, 'usardia': False})

        contexto['form'] = form
        contexto['turnos'] = turnos
        print('Filtro: ', contexto['filtro'])
        return render(request, "turnos/listado.html", contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))
    
def CrearTurno(request):
    contexto = logueadoComo(request, ['gerencia', 'secretaria'])
    if contexto: 
        contexto['accion'] = 'Crear'
        form = FormCrearTurno(request.POST or None)
        contexto['form'] = form
        if request.method == 'POST':
            if form.is_valid():
                form.save()    
                contexto['resultado'] = 'form valido'
                return HttpResponseRedirect(reverse("turnos:listado"))
            else:
                contexto['resultado'] = 'form no valido'
                return render(request, 'turnos/detalle.html', contexto)
        else:
            contexto['resultado'] = 'form nuevo'
            return render(request, 'turnos/detalle.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def ModificarTurno(request, id_turno):
    contexto = logueadoComo(request, ['gerencia', 'secretaria'])
    if contexto: 
        contexto['accion'] = 'Modificar'
        try:
            turno = get_object_or_404(Turno, id = id_turno)
        except Exception:
            raise Http404('no existe el turno')

        if request.method == 'POST':
            form = FormCrearTurno(request.POST, instance = turno)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('turnos:listado'))
        else:
            form = FormCrearTurno(instance = turno)
            contexto['form'] = form
            return render(request, 'turnos/detalle.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def EliminarTurno(request, id_turno):
    contexto = logueadoComo(request, ['gerencia', 'secretaria'])
    if contexto:     
        try:
            turno = get_object_or_404(Turno, id = id_turno)
            contexto['turno'] = turno
        except Exception:
            raise Http404('no existe el turno')

        if request.method == 'POST':
            turno.delete()
            return HttpResponseRedirect(reverse('turnos:listado'))
        else:
            return render(request, 'turnos/eliminar.html', contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def AlternarAtendido(request, id_turno):
    contexto = logueadoComo(request, ['gerencia', 'profesional', 'secretaria'])
    if contexto: 
        try:
            turno = get_object_or_404(Turno, id = id_turno)
        except Exception:
            raise Http404('no existe el turno')
        turno.atendido = not turno.atendido
        turno.save()
        return HttpResponseRedirect(reverse('turnos:listado'))
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

turnos/templates/turnos/detalle.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - {{accion}} Turno {% endblock title %} 

{% block contenido %}
    <br>
    <h3>{{ accion }} Turno</h3>
    <br>
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <br>
        <input type="submit" class="btn btn-primary" value="Guardar"> 
        <input type="button" class="btn btn-secondary"  name="cancelar" value="Cancelar" onClick="window.location.href={% url 'turnos:listado' %};" />
    </form>
{% endblock contenido %}

turnos/templates/turnos/eliminar.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Eliminar Turno{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Eliminar Turno</h3>
    <br>
    <div>Realmente desea eliminar el turno del paciente <strong>{{ turno.paciente }}</strong> con 
        <strong>Dr {{ turno.doctor.last_name|title }}, {{ turno.doctor.first_name|title }} </strong>
        para el dia {{ turno.fecha }} a la hora {{ turno.hora_str }} ?</div>
    <br>
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <input type="submit" class="btn btn-primary" value="Eliminar"> 
        <input type="button" class="btn btn-secondary" name="cancelar" value="Cancelar" onClick="window.location.href={% url 'turnos:listado' %};" />
    </form>
{% endblock contenido %}

turnos/templates/turnos/listado.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Turnos{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Turnos</h3>
    <p>
    {% if 'secretaria' in grupos or 'gerencia' in grupos %} 
    <a class="badge badge-primary " href="{% url 'turnos:crear' %}">nuevo</a>
    {% endif %}
    <a class="badge badge-secondary" data-toggle="collapse" href="#cuadrofiltro" role="button" aria-expanded="false" aria-controls="collapseExample"> Filtro: {{filtro}} </a>
    </p>
    <div class="collapse" id="cuadrofiltro">
    <div class="card card-body">
        <form method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{ form.as_p }} 
            <input type="submit" class="btn btn-primary" value="Filtrar"> 
            <input type="button" class="btn btn-secondary" name="reestablecer" value="Reestablecer" onClick="window.location.href={% url 'turnos:listado' %};" />
        </form>
    </div>
    </div>
    <p>
    <ul class="list-group">
        {% for un_turno in turnos %}
            <li class="list-group-item"> 
                <div class="text-info">{{un_turno.fecha}}, {{un_turno.hora_str}}Hs</div>
                <div>Paciente: <strong>{{ un_turno.paciente }}</strong> <small class="text-muted"> - DNI: {{ un_turno.paciente.dni }} </small> </div>
                <div>Medico: {{ un_turno.doctor.last_name|title }}, {{ un_turno.doctor.first_name|title }} </div>
                <div>
                    {% if un_turno.atendido %} 
                        <a href="{% url 'turnos:alternaratendido' un_turno.id %}" class="badge badge-success badge-pill">
                        Atendido
                    {% else %}
                        <a href="{% url 'turnos:alternaratendido' un_turno.id %}" class="badge badge-secondary badge-pill">
                        No atendido
                    {% endif %}
                    </a>

                    {% if 'secretaria' in grupos or 'gerencia' in grupos %} 
                        <a href="{% url 'turnos:modificarturno' un_turno.id %}" class="badge badge-light">modificar</a> <a href="{% url 'turnos:eliminarturno' un_turno.id %}" class="badge badge-light">eliminar</a>  
                    {% endif %}
                    {% if 'profesional' in grupos or 'gerencia' in grupos %} 
                        <a href="{% url 'historial:historialpaciente' un_turno.paciente_id %}" class="badge badge-light">historia clinica</a>
                    {% endif %}
                </div>
            </li>
        {% empty %}
            <li> no hay turnos para el filtro seleccionado </li>
        {% endfor %}
    </ul>
{% endblock contenido %}