TrabajoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('paginas.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('turnos/', include('turnos.urls')),
    path('historial/', include('historial.urls')),
    path('productos/', include('productos.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('taller/', include('taller.urls')),
    path('gerencia/', include('gerencia.urls')),
]

gerencia/urls.py
from django.urls import path
from . import views

app_name = 'gerencia'

urlpatterns = [
    path("", views.Informes, name="informes"),
    path("informes/<int:num_informe>", views.Informe, name="informe"),
]

paginas/urls.py
from django.urls import path
from .views import *

app_name = 'paginas'

urlpatterns = [
    path('', vista_inicio, name='inicio'),
    path('acercade/', vista_acercade, name='acercade'),
]

pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("crear", views.CrearPedido, name="crearpedido"),
    path("<int:id_pedido>", views.VerPedido, name="verpedido"),
    path("<int:id_pedido>/modificar", views.ModificarPedido, name="modificarpedido"),
    path("<int:id_pedido>/eliminar", views.EliminarPedido, name="eliminarpedido"),
    path("seleccionaritem", views.SeleccionarItem, name="seleccionaritem"),
    path("<int:id_pedido>/agregaritem/<int:id_item>", views.AgregarItem, name="agregaritem"),
    path("<int:id_pedido>/modificaritem/<int:id_itempedido>", views.ModificarItem, name="modificaritem"),
]

taller/urls.py
from django.urls import path
from . import views

app_name = 'taller'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("<int:id_pedido>/verpedido", views.VerPedido, name="verpedido"),
    path("<int:id_pedido>/cambiarestado", views.CambiarEstado, name="cambiarestado"),
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("crear/", views.CrearTurno, name="crear"),
    path("<int:id_turno>/modificar", views.ModificarTurno, name="modificarturno"),
    path("<int:id_turno>/eliminar", views.EliminarTurno, name="eliminarturno"),
    path("<int:id_turno>/alternaratendido", views.AlternarAtendido, name="alternaratendido"),
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.vista_login, name="login"),
    path("logout", views.vista_logout, name="logout")
]

paginas/models.py
from django.db import models

# Create your models here.

paginas/views.py
from django.shortcuts import render
from usuarios.utilidades import estado_auth

def vista_inicio(request):
    return render(request, 'paginas/inicio.html', estado_auth(request))

def vista_acercade(request):
    return render(request, 'paginas/acercade.html', estado_auth(request))

paginas/templates/paginas/_layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <title>
      {% block title %} 
        titulo de pagina 
      {% endblock title %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-between">
      <a class="navbar-brand" href={% url 'paginas:inicio' %}>
        {% load static %}
        <img src="{% static 'img/icono.png' %}" width="30" height="30" alt="">
      </a>
      <a class="navbar-brand" href={% url 'paginas:inicio' %}>Clinica Optométrica Potter</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar0" aria-controls="navbar0" aria-expanded="true" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbar0">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'paginas:inicio' %}">inicio<span class="sr-only">(current)</span></a>
          </li>
          
          {% if 'ventas' in grupos or 'gerencia' in grupos %} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'productos:listado' %}">productos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pedidos:listado' %}">pedidos</a>
            </li>
            {% if id_pedidoactual %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pedidos:verpedido' id_pedidoactual %}"><strong>pedido</strong></a>
              </li>
            {% endif %}
          {% endif %}

          {% if 'secretaria' in grupos or 'gerencia' in grupos %} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pacientes:listado' %}">pacientes</a>
            </li>
          {% endif %}
          {% if 'secretaria' in grupos or 'profesional' in grupos  or 'gerencia' in grupos %} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'turnos:listado' %}">turnos</a>
            </li>
          {% endif %}

          {% if 'profesional' in grupos or 'gerencia' in grupos %} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'historial:listado' %}">historial clinico</a>
            </li>
          {% endif %}

          {% if 'taller' in grupos or 'gerencia' in grupos %} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'taller:listado' %}">pedidos taller</a>
            </li>
          {% endif %}

          {% if 'gerencia' in grupos%} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gerencia:informes' %}">informes</a>
            </li>
          {% endif %}

          {% if autenticado %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuarios:logout' %}">logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuarios:login' %}">login</a>
            </li>
          {% endif %}
          
          {% comment %} <li class="nav-item">
            <a class="nav-link disabled" href="#">inactivo</a>
          </li> 
          {% endcomment %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'paginas:acercade' %}">
            {% if user.is_authenticated %}
              <strong>{{ usuario }}</strong>
            {% else %}
              acerca de
            {% endif %}
            </a>
          </li>

        </ul>
      </div>
    </nav>

    <div class="container">{% block contenido %} {% endblock contenido %}</div>


    <footer class="page-footer font-small mdb-color pt-4">
      <div class="container text-center text-md-left">
        <hr>
        <div class="row d-flex align-items-center">
          <div class="col-md-7 col-lg-8">
            <p class="text-center text-md-left">© 2020 <a href={% url 'paginas:inicio' %}>Clinica Potter</a></p>
          </div>
        </div>
      </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

paginas/templates/paginas/acercade.html
<!-- templates/inicio.html -->
{% extends 'paginas/_layout.html' %} 

{% block title %}Trabajo Practico Final - Acerca de{% endblock title %} 

{% block contenido %} 
  <style>
    {% if 'profesional' in grupos %}
      #spro { background-color: #ffffbb; }
    {% endif %}
    {% if 'secretaria' in grupos %}
      #ssec { background-color: #ffffbb; }
    {% endif %}
    {% if 'ventas' in grupos %}
      #svta { background-color: #ffffbb; }
    {% endif %}
    {% if 'taller' in grupos %}
      #stal { background-color: #ffffbb; }
    {% endif %}
    {% if 'gerencia' in grupos %}
      #sger { background-color: #ffffbb; }
    {% endif %}
  </style>
  
  <br>
  <h3 class="cover-heading"><b>Desarrollo Web Full Stack con Python y JavaScript
</b></h3>
  <p class="lead">
    TRABAJO FINAL CURSO 2020
  </p>

  <h3>Sesión actual</h3>
  {% if autenticado %}
    <div>Autenticado como: {{ request.user.last_name|title }},  {{ request.user.first_name|title }}. Grupo: {{ grupos_v|title }}.</div>
    <div>Último ingreso: {{ request.user.last_login }}.</div>
  {% else %}
      <div>No autenticado</div>
  {% endif %} 

  <div>
    <br>
    <h3>Enunciado del Problema a Resolver</h3>
    <p class="text-justify">Una clínica de Optometría necesita un sistema web en Django que le permita gestionar el
    diagnóstico de sus pacientes y la venta de los productos Ópticos para los mismos. Para ello
    se requiere: </p>
    <ol class="text-justify">
      <li>
        Un sistema con un login de usuario con los siguientes roles:
        <ol class="text-justify" style="list-style-type:lower-alpha">
          <li  id='ssec'>Secretaría</li>
          <li  id='spro'>Profesional medico</li>
          <li id='svta'>Ventas</li>
          <li id='stal'>Taller</li>
          <li id='sger'>Gerencia</li>
        </ol>  
      </li>
      <li>
        El sistema gestionará tres Modelos esenciales:
        <ol class="text-justify" style="list-style-type:lower-alpha">
          <li id='ssec'>Turnos</li>
          <li id='svta'>Pedidos</li>
          <li id='ssec'>Pacientes</li>
        </ol>
      </li>
      <li id='ssec'>El rol de Secretaría permite agregar, modificar o eliminar los turnos de los Pacientes.</span></li>
      <span id='spro'>
      <li id='spro'>Cada Paciente tiene su historial médico (solo el Profesional médico puede agregar
          Observaciones al historial médico).</li>
      <li id='spro'>Cada Profesional médico puede ver el listado de Pacientes filtrando por día, mes o año.</span></li>
      <li id='spro'>El Profesional médico solo puede ver los Pacientes asignados a él.</li>
      <li id='svta'>El rol de Ventas puede generar un pedido para el Paciente, donde detalla el Producto
          que quiere adquirir, el precio (pueden ser más de un producto), un subtotal, tipo de
          pago (tarjeta de crédito, debido, billetera virtual o efectivo).
        <ol class="text-justify" style="list-style-type:lower-alpha">
          <li>El producto tiene nombre, si está clasificado como Lente tendrá la opción de
              Lejos/Cerca, Izquierda/Derecha, si incluye Armazón o no.</li>
          <li>Una vez que se genera el pedido queda en estado “Pendiente”.</li>
          <li>Luego el rol de Ventas puede cambiar el estado a “Pedido” o mandarlo a “Taller”.</li>
        </ol>
      </li>
      <li id='stal'>El rol de Taller solo visualiza la lista de pedidos (con todos los detalles del producto sin
          los precios). El Taller puede confirmar cambiando el estado del pedido a “Finalizado”.</li>
      <li id='sger'>Gerencia puede visualizar todos los datos y necesita los siguientes reportes:
        <ol class="text-justify" style="list-style-type:lower-alpha">
          <li>Pacientes que asistieron a los turnos en la semana/mes.</li>
          <li>Pacientes que no asistieron a los turnos en la semana/mes.</li>
          <li>Pacientes que hicieron por lo menos un Pedido en la semana/mes.</li>
          <li>Productos más vendidos en el mes.</li>
          <li>Ventas totales por mes clasificadas por Vendedores.</li>
        </ol>
        
      </li>
    </ol>

  </div>
  <br><br>
{% endblock contenido %}

paginas/templates/paginas/inicio.html
<!-- templates/inicio.html -->
{% extends 'paginas/_layout.html' %} 

{% block title %}Clinica optométrica Potter{% endblock title %} 

{% block contenido %} 
  {% load static %}
  <br>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'img/lentes01.jpg' %}" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Clinica Optométrica Potter</h5>
        <p>Las mejores marcas en marcos recetados y anteojos de sol. Cristales de calidad, lentes de contacto y accesorios</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/docs01.jpg' %}" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Seriedad y servicio</h5>
        <p>Te ofrecemos atención de calidad. Somos la mejor opción para quienes priorizan la salud visual, bienestar y estética.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'img/docs03.jpg' %}" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>Equipo interdiciplinario</h5>
        <p>Todo nuestro personal cuenta con la mas amplia experiencia en optica de vanguardia, capacitados para interpretar sus necesidades y proponerle las mejores alternativas con la última tecnologia.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock contenido %}