TrabajoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('paginas.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('turnos/', include('turnos.urls')),
    path('historial/', include('historial.urls')),
    path('productos/', include('productos.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('taller/', include('taller.urls')),
    path('gerencia/', include('gerencia.urls')),
]

historial/urls.py
from django.urls import path
from . import views

app_name = 'historial'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("<int:id_paciente>", views.HistorialPaciente, name="historialpaciente"),
    path("<int:id_paciente>/crear", views.CrearObservacion, name="crearobservacion"),
    path("modificarobservacion/<int:id_observacion>", views.ModificarObservacion, name="modificarobservacion"),
    path("eliminarobservacion/<int:id_observacion>", views.EliminarObservacion, name="eliminarobservacion"),
]

taller/urls.py
from django.urls import path
from . import views

app_name = 'taller'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("<int:id_pedido>/verpedido", views.VerPedido, name="verpedido"),
    path("<int:id_pedido>/cambiarestado", views.CambiarEstado, name="cambiarestado"),
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'

urlpatterns = [
    path("", views.Listado, name="listado"),
    path("crear/", views.CrearTurno, name="crear"),
    path("<int:id_turno>/modificar", views.ModificarTurno, name="modificarturno"),
    path("<int:id_turno>/eliminar", views.EliminarTurno, name="eliminarturno"),
    path("<int:id_turno>/alternaratendido", views.AlternarAtendido, name="alternaratendido"),
]

historial/models.py
from django.db import models
from pacientes.models import Paciente
from django.contrib.auth.models import User, Group

    
class HistorialObservacion(models.Model):    
    paciente = models.ForeignKey(Paciente, on_delete = models.RESTRICT, related_name='hcpacientes')
    doctor = models.ForeignKey(User, on_delete = models.RESTRICT, related_name='hcdoctores')
    fecha = models.DateField()
    observacion = models.CharField(max_length=1000)

    def __str__(self):
        return f'{self.fecha}: {self.observacion} '

historial/forms.py
from django import forms
from django.forms.widgets import NumberInput
from django.contrib.auth.models import User
from pacientes.models import Paciente
from .models import HistorialObservacion
from django.forms import ModelChoiceField
import datetime

class MyModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.first_name}, {obj.last_name}'

class FormCrearObservacion(forms.ModelForm):
    class Meta:
        model = HistorialObservacion
        fields = ['fecha',  'observacion']
    
    fecha = forms.DateField(initial = datetime.date.today, widget = NumberInput(attrs={'autofocus': 'autofocus', 'type': 'date', 'class': 'form-control'}))
    observacion = forms.CharField(widget = forms.Textarea(attrs = {'class': 'form-control'})) 

opciones_fecha = [('0', 'Usar solo año'), ('1', 'Usar año y mes'), ('2', 'Usar año, mes y dia')]

historial/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django import forms
from datetime import datetime
from usuarios.utilidades import *
from .models import HistorialObservacion
from pacientes.models import Paciente
from turnos.models import Turno
from .forms import FormCrearObservacion

def Listado(request):
    contexto = logueadoComo(request, ['gerencia', 'profesional'])
    if contexto: 
        if 'gerencia' in contexto['grupos']:
            pacientes = Turno.objects.filter() # el gerente ve todos los historiales
        else:
            pacientes = Turno.objects.filter(doctor = request.user) # los doctores solo ven aquienes atendieron
        pacientesunicos = []
        for pc in pacientes:
            if pc.paciente not in pacientesunicos:
                pacientesunicos.append(pc.paciente)
        contexto['pacientes'] = pacientesunicos
        return render(request, "historial/listadopacientes.html", contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def HistorialPaciente(request, id_paciente):
    contexto = logueadoComo(request, ['gerencia', 'profesional'])
    if contexto: 
        try:
            print('doc id: ', contexto['id_usuario'])
            print('paciente id: ', id_paciente)

            paciente = get_object_or_404(Paciente, id = id_paciente) # verifica exstencia de paciente
            turnos = Turno.objects.filter(paciente_id = id_paciente, doctor_id = contexto['id_usuario']) # verifica que el doctor haya atendido al paciente 
        except Exception:
            raise Http404('no existe el paciente ')

        contexto['paciente'] = paciente
        observaciones = HistorialObservacion.objects.filter(paciente_id = id_paciente)
        contexto['observaciones'] = observaciones
        return render(request, "historial/historialpaciente.html", contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def CrearObservacion(request, id_paciente):
    contexto = logueadoComo(request, ['gerencia', 'profesional']) # solo profesional accede a esto
    if contexto: # hay contexto entonces es profesional 
        contexto['accion'] = 'Crear' 
        try: # se busca el paciente y luego turnos del paciente filtrados con el profesional actual
            paciente = get_object_or_404(Paciente, id = id_paciente)
            turnos = Turno.objects.filter(paciente_id = id_paciente, doctor_id = contexto['id_usuario'])
            if turnos.count() == 0: # no hay registros?
                raise Http404()  
        except Exception: # no hay pacientes atendidos por el doctor
            raise Http404('no existe el paciente o doctor')
        contexto['paciente'] = paciente

        form = FormCrearObservacion(request.POST or None)
        print('Formulario: ', form)
        if request.method == 'POST':
            if form.is_valid():
                doctor = User.objects.get(id = contexto['id_usuario'])
                fecha = request.POST['fecha']
                observacion = HistorialObservacion(paciente = paciente, doctor = doctor, fecha = fecha, observacion = request.POST['observacion'])
                observacion.save()
                return redirect("historial:historialpaciente", id_paciente = id_paciente)
        else:
            contexto['form'] = form 
            return render(request, "historial/detalleobservacion.html", contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def ModificarObservacion(request, id_observacion):
    contexto = logueadoComo(request, ['gerencia', 'profesional']) # solo profesional accede a esto
    if contexto: # hay contexto entonces es profesional 
        contexto['accion'] = 'Modificar' 
        try: # se busca la observacion y paciente
            observacion = get_object_or_404(HistorialObservacion, id = id_observacion)
            paciente = observacion.paciente
            if not observacion.doctor_id == contexto['id_usuario']:
                raise()
        except Exception:
            raise Http404('no existe la observacion')
        # se agregan los resultados al contexto
        contexto['observacion'] = observacion
        contexto['paciente'] = paciente

        if request.method == 'POST': # el usuario confirmó la modificacion mediante POST?
            form = FormCrearObservacion(request.POST, instance = observacion)
            if form.is_valid():
                observacion.save()
                return redirect("historial:historialpaciente", id_paciente = paciente.id) 
        else: # es la carga inicial de la pagina modificar
            form = FormCrearObservacion(instance = observacion)
            print('>>> form: ', form)
            contexto['form'] = form 
            return render(request, "historial/detalleobservacion.html", contexto)
    else:
        return HttpResponseRedirect(reverse("paginas:inicio"))

def EliminarObservacion(request, id_observacion):
    contexto = logueadoComo(request, ['gerencia', 'profesional']) # solo profesional accede a esto
    if contexto: # hay contexto entonces es profesional
        try: # se busca la observacion y paciente
            observacion = get_object_or_404(HistorialObservacion, id = id_observacion)
            paciente = observacion.paciente
        except Exception:
            raise Http404('no existe la observacion')
        # se agregan los resultados al contexto
        contexto['observacion'] = observacion
        contexto['paciente'] = paciente

        if request.method == 'POST': # el usuario confirmó la eliminacion mediante POST?
            observacion.delete()
            return redirect("historial:historialpaciente", id_paciente=paciente.id) 
        else: # es la carga inicial de la pagina eliminar
            return render(request, "historial/eliminarobservacion.html", contexto)
    else: #no es profesional
        return HttpResponseRedirect(reverse("paginas:inicio"))

historial/templates/historial/detalleobservacion.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - {{accion}} Observacion {% endblock title %} 

{% block contenido %}
    <br>
    <h3>Historial de {{ paciente }} </h3>
    <h3>{{accion}} Observacion </h3>
    <br>
    <ul>
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <br>
        <input type="submit" class="btn btn-primary" value="Guardar"> 
        <input type="button" class="btn btn-secondary"  name="cancelar" value="Cancelar" onClick="location.href='{% url 'historial:historialpaciente' id_paciente=paciente.id %}';" />
                                                                                         
    </form>
{% endblock contenido %}

historial/templates/historial/eliminarobservacion.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Eliminar Observacion{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Eliminar Observacion</h3>
    <br>
    <ul class="list-group">
        <li class="list-group-item list-group-item-action flex-column align-items-start"> 
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">
                    <div>Paciente: {{ paciente }}</div>
                </h5>
                <small class="text-muted">{{observacion.fecha}} </small>
            </div>
            <div>Medico: {{observacion.doctor.last_name|title}}, {{observacion.doctor.first_name|title}}</div>                    
            <div>Observacion: 
                <ul>
                    <li>
                        <p class="mb-1">{{observacion.observacion}}</p>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
    <br>
    <div>Realmente desea eliminar la observacion?</div>
    <br>
    <form method="POST" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <input type="submit" class="btn btn-primary" value="Eliminar"> 
        <input type="button" class="btn btn-secondary"  name="cancelar" value="Cancelar" onClick="location.href='{% url 'historial:historialpaciente' id_paciente=paciente.id %}';" />
                                                                                         
    </form>
{% endblock contenido %}

historial/templates/historial/historialpaciente.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - {{accion}} Historial clinico de paciente {% endblock title %} 

{% block contenido %}
    <br>
    <h3>Historial de {{ paciente }} - dni: {{ paciente.dni }}</h3>
    <a class="badge badge-primary " href="{% url 'historial:crearobservacion' paciente.id %}">agregar observacion</a>
    <br><br>
    <ul class="list-group">
    {% for observacion in observaciones %}
        <li class="list-group-item list-group-item-action flex-column align-items-start"> 
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Medico: {{observacion.doctor.last_name|title}}, {{observacion.doctor.first_name|title}}</h5>
                <small class="text-muted">{{observacion.fecha}} </small>
            </div>

            <div>Observacion: 
                <br>
                <ul>
                    <li>
                        <p class="mb-1">{{observacion.observacion}}</p>
                    </li>
                </ul>
            </div>

            {% if observacion.doctor.id == id_usuario %}
            <div>
                <a href="{% url 'historial:modificarobservacion' observacion.id %}" class="badge badge-secondary">modificar</a>
                <a href="{% url 'historial:eliminarobservacion' observacion.id %}" class="badge badge-secondary">eliminar</a>
            </div> 
            {% endif %}
        </li>
    {% empty %}
        <li> no hay observaciones para el paciente </li>
    {% endfor %}
    </ul>
{% endblock contenido %}

historial/templates/historial/listadopacientes.html
{% extends "paginas/_layout.html" %}

{% block title %}Trabajo Practico Final - Historial Clinico{% endblock title %} 

{% block contenido %}
    <br>
    <h3>Historiales de Pacientes</h3>
    <div>Medico: {{usuario.last_name|title}}, {{usuario.first_name|title}}</div>
    <div class="collapse" id="cuadrofiltro">
    <div class="card card-body">
        <form method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{ form.as_p }} 
            <input type="submit" class="btn btn-primary" value="Filtrar"> 
            <input type="button" class="btn btn-secondary" name="reestablecer" value="Reestablecer" onClick="window.location.href={% url 'turnos:listado' %};" />
        </form>
    </div>
    </div>
    <p>

    <ul class="list-group">
        {% for un_paciente in pacientes %}
            <li class="list-group-item"> 
                <div>Paciente id: {{un_paciente.id}} - <strong>{{un_paciente.apellido}}, {{un_paciente.nombre}}</strong> - dni: {{un_paciente.dni}}</div>
                <div>
                    <a href="{% url 'historial:historialpaciente' un_paciente.id %}" class="badge badge-light">historia clinica</a>
                </div>
            </li>
        {% empty %}
            <li> no hay pacientes atendidos </li>
        {% endfor %}
    </ul>
{% endblock contenido %}